# Generated by Django 5.2.6 on 2025-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igati_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='weeeeeeeee', max_length=128),
        ),
    ]
